### PR TITLE
More robust handling of userAgentData, fix WebPushDeviceAdmin

### PR DESCRIPTION
**Pull request by simonkern**
Relevant userAgentData ist not always stored in navigator.userAgentData.brands[0]

It is necessary to loop through all available navigator.userAgentData.brands and try to find the relevant entry. In case of Edge (and maybe in case of other chromium-based browsers too) it is also necessary to ignore any matches regarding chrome...

addresses #640

### CODE REVIEW

**Comment by simonkern** [comment]
Field "device_id" is not available for WebPushDevices. Instead I added "browser" to ListView and "registration_id" to search_fields

**Review by auvipy — CHANGES_REQUESTED** [review]
can you provide some tests for the changes please?

**Comment by simonkern** [comment]
@auvipy what do you have in mind? Except for the field changes in the broken admin, these are only changes to the README.

**Comment by auvipy** [comment]
@dismine

**Comment by dismine** [comment]
New ``function loadVersionBrowser`` works for me. Already ported to my website.

**Review by auvipy — APPROVED** [review]

**Pull request merged**
