### PR TITLE
Release 2.0.0

### PR DESCRIPTION
**Pull request by odinuge**
We should probably write a bit more in the changelog before merging! Feel free to create a PR to this branch, `release-v1.7.0`, or push your commits if you are a part of jazzband, or just comment.. :smile: 

Commits since last release:
```
* 455a027 (HEAD -> release-v1.7.0, upstream/release-v1.7.0, v1.7.0) Release 1.7.0
* 2ce2837 (upstream/master) Add support for python 3.7 (#492)
* a73253a Fix problems with CI (#501)
* c4a0d71 README: Update APNs link
* 9182958 flake8: Ignore E503 (use Black style)
* 4962944  Add FCM channels support for custom notification sound on Android Oreo
* 45f0e96 Fix APN bulk messages
* 6f7b80d Avoid mutating arguments in `gcm._cm_send_request`
* e335ac6 Fix error when send a message and the device is not active
* 600495b gcm: Simplify some code
* 8c73a77 Fix README missing paragraph break confusion
* 1be2f2a Add Jazzband contributing guidelines
* 2ae27f9 Update repository URLs (again)
* 5954578 Cleanup overzealous tests
* 9f71624 Move Python 2 compatibility imports to push_notifications.compat
* 3052927 Update setup.cfg and DRF support notice
* c821ec9 Convert changelog to Markdown
* 86409f6 Move AUTHORS to ACKNOWLEDGEMENTS.md
* 803caa9 Clean up code style issues
* f625921 Move base NotificationError to push_notifications.exceptions
* c4785a3 Drop apns_errors, use exception class name instead
* a3bda0a Clean up imports and switch to isort+flake8-isort
* cee4160 (tag: 1.6.0) Release 1.6.0
```

Because of the breaking changes, we will bump to version `2.0.0`.

### CODE REVIEW

**Comment by odinuge** [comment]
Hmm. Since https://github.com/jazzband/django-push-notifications/commit/f625921d0e086fdb572a0890396c4cc3e7719576 is breaking, we should most likely bump to `2.0`. I guess a lot of users use the exception and don't have tests verifying that their code works, so it might break some production systems if people update without reading the changelog.

Any thoughts?

**Comment by auvipy** [comment]
yes right

**Comment by wtayyeb** [comment]
Hi, could you please see https://github.com/jazzband/django-push-notifications/pull/507 as it is a very minor change that solve a really big bug in `WebPushDevice.send_message()` and include it in this release?

**Comment by odinuge** [comment]
Hi @wtayyeb! Yes, that is no problem, as the tag is still not set, and the PR just got merged. 😄 Thank you so much for the contribution!

**Comment by odinuge** [comment]
Can you try to formulate an entry for the changelog for your patch @wtayyeb? This is the rest of the current changelog: https://github.com/jazzband/django-push-notifications/pull/502/files#diff-4ac32a78649ca5bdd8e0ba38b7006a1e

**Comment by wtayyeb** [comment]
Hi @odinuge, I create new PR https://github.com/jazzband/django-push-notifications/pull/508, for this. its your turn to merge it.

**Comment by odinuge** [comment]
Thanks! Hopefully we can release v2.0.0 soon 😄

**Pull request merged**
