### PR TITLE
 Added Safari browser to web-push

### PR DESCRIPTION
**Pull request by Sergey-Yalovoy**
I have studied the problems with Safari and offer my solution.
I tested my solution in my project, it works great.

### CODE REVIEW

**Comment by jamaalscarlett** [comment]
Looks good @Sergey-Yalovoy .  If you rebase against master, I have fixed the failing test actions.

**Comment by jamaalscarlett** [comment]
Will this require a new migration?  See: https://github.com/jazzband/django-push-notifications/blob/master/push_notifications/migrations/0008_webpush_add_edge.py

**Comment by azmeuk** [comment]
As I understand, with #674 makes WP browser generic, so this PR won't be needed.

**Comment by jamaalscarlett** [comment]
Closing as this is addressed by https://github.com/jazzband/django-push-notifications/pull/674

**Pull request closed without merging**
