### PR TITLE
Add instructions for APNS pem cert generation

### PR DESCRIPTION
**Pull request by lukeburden**
Each time I need to renew certificates or setup a new project I waste time
fighting with Apple generating a certificate then digging around for decent
instructions for converting that exported certificate to a usable PEM format.

I'd like to begin documenting a sensible, repeatable method for at least the
conversion here.

### CODE REVIEW

**Comment by jamaalscarlett** [comment]
@matthewh @kit-cat I don't use APNS, can you take a look at this?

**Comment by jleclanche** [comment]
@jamaalscarlett the docs are correct as far as generating a PEM file goes, but can it be split from the README? just have it in a separate file in docs/

**Comment by lukeburden** [comment]
@jleclanche could this be merged? Perhaps factoring pieces out into a separate docs directory could come as a separate effort.

**Comment by odinuge** [comment]
Hi @lukeburden! I cherry-picked your commit and fixed the conflicts, and merged it into master via #504. Thanks for the contribution! :smile: 

Ill just close this.

**Comment by lukeburden** [comment]
No worries, thanks for getting it in there. Hopefully it's not too stale after 2 years. :)

**Pull request closed without merging**
